displayName: Scriptable Middleware Plugin
type: middleware

import: github.com/Gizeta/simplescript4traefik

summary: 'A experiment middleware for traefik running Lisp-liked script'

testData:
  code: |
    (if (! (str_contains (get_req_path) "pass"))
      (halt 403 "Not Allowed")
      ((set_req_header "pass" "1")
        (run_next)))
